using System.Collections.Generic;
using Content.Shared.Loudspeaker;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using static Robust.Client.UserInterface.Controls.BaseButton;
using FancyWindow = Content.Client.UserInterface.Controls.FancyWindow;

namespace Content.Client.Loudspeaker.UI;

[GenerateTypedNameReferences]
public sealed partial class LoudspeakerMenu : FancyWindow
{
    public event Action? OnFilePressed;
    public event Action? OnPlayPressed;
    public event Action? OnStopPressed;
    public event Action<bool>? OnLoopToggled;
    public event Action<byte, byte>? OnInstrumentChanged;

    private readonly Dictionary<string, CheckBox> _groupCheckBoxes = new();
    private bool _playing;

    // General MIDI instrument names (program 0-127, bank 0)
    private static readonly string[] MidiInstruments =
    {
        "Acoustic Grand Piano", "Bright Acoustic Piano", "Electric Grand Piano", "Honky-tonk Piano",
        "Electric Piano 1", "Electric Piano 2", "Harpsichord", "Clavinet",
        "Celesta", "Glockenspiel", "Music Box", "Vibraphone",
        "Marimba", "Xylophone", "Tubular Bells", "Dulcimer",
        "Drawbar Organ", "Percussive Organ", "Rock Organ", "Church Organ",
        "Reed Organ", "Accordion", "Harmonica", "Tango Accordion",
        "Acoustic Guitar (nylon)", "Acoustic Guitar (steel)", "Electric Guitar (jazz)", "Electric Guitar (clean)",
        "Electric Guitar (muted)", "Overdriven Guitar", "Distortion Guitar", "Guitar Harmonics",
        "Acoustic Bass", "Electric Bass (finger)", "Electric Bass (pick)", "Fretless Bass",
        "Slap Bass 1", "Slap Bass 2", "Synth Bass 1", "Synth Bass 2",
        "Violin", "Viola", "Cello", "Contrabass",
        "Tremolo Strings", "Pizzicato Strings", "Orchestral Harp", "Timpani",
        "String Ensemble 1", "String Ensemble 2", "Synth Strings 1", "Synth Strings 2",
        "Choir Aahs", "Voice Oohs", "Synth Choir", "Orchestra Hit",
        "Trumpet", "Trombone", "Tuba", "Muted Trumpet",
        "French Horn", "Brass Section", "Synth Brass 1", "Synth Brass 2",
        "Soprano Sax", "Alto Sax", "Tenor Sax", "Baritone Sax",
        "Oboe", "English Horn", "Bassoon", "Clarinet",
        "Piccolo", "Flute", "Recorder", "Pan Flute",
        "Blown Bottle", "Shakuhachi", "Whistle", "Ocarina",
        "Lead 1 (square)", "Lead 2 (sawtooth)", "Lead 3 (calliope)", "Lead 4 (chiff)",
        "Lead 5 (charang)", "Lead 6 (voice)", "Lead 7 (fifths)", "Lead 8 (bass + lead)",
        "Pad 1 (new age)", "Pad 2 (warm)", "Pad 3 (polysynth)", "Pad 4 (choir)",
        "Pad 5 (bowed)", "Pad 6 (metallic)", "Pad 7 (halo)", "Pad 8 (sweep)",
        "FX 1 (rain)", "FX 2 (soundtrack)", "FX 3 (crystal)", "FX 4 (atmosphere)",
        "FX 5 (brightness)", "FX 6 (goblins)", "FX 7 (echoes)", "FX 8 (sci-fi)",
        "Sitar", "Banjo", "Shamisen", "Koto",
        "Kalimba", "Bagpipe", "Fiddle", "Shanai",
        "Tinkle Bell", "Agogo", "Steel Drums", "Woodblock",
        "Taiko Drum", "Melodic Tom", "Synth Drum", "Reverse Cymbal",
        "Guitar Fret Noise", "Breath Noise", "Seashore", "Bird Tweet",
        "Telephone Ring", "Helicopter", "Applause", "Gunshot",
    };

    public LoudspeakerMenu()
    {
        RobustXamlLoader.Load(this);

        FileButton.OnPressed += _ => OnFilePressed?.Invoke();
        PlayButton.OnPressed += _ => OnPlayPressed?.Invoke();
        StopButton.OnPressed += _ => OnStopPressed?.Invoke();
        LoopButton.OnToggled += args => OnLoopToggled?.Invoke(args.Pressed);

        StopButton.Disabled = true;

        // Populate instrument dropdown.
        for (var i = 0; i < MidiInstruments.Length; i++)
        {
            InstrumentSelect.AddItem(MidiInstruments[i], i);
        }

        InstrumentSelect.OnItemSelected += args =>
        {
            InstrumentSelect.SelectId(args.Id);
            OnInstrumentChanged?.Invoke((byte) args.Id, 0);
        };
    }

    public void PopulateGroups(List<LoudspeakerGroupInfo> groups)
    {
        GroupContainer.RemoveAllChildren();
        _groupCheckBoxes.Clear();

        foreach (var group in groups)
        {
            var checkBox = new CheckBox
            {
                Text = $"{group.Name} ({group.SpeakerCount})",
            };
            _groupCheckBoxes[group.GroupId] = checkBox;
            GroupContainer.AddChild(checkBox);
        }
    }

    public List<ProtoId<LoudspeakerGroupPrototype>> GetSelectedGroups()
    {
        var selected = new List<ProtoId<LoudspeakerGroupPrototype>>();

        foreach (var (groupId, checkBox) in _groupCheckBoxes)
        {
            if (checkBox.Pressed)
                selected.Add(groupId);
        }

        return selected;
    }

    public void SetPlaying(bool playing, List<ProtoId<LoudspeakerGroupPrototype>>? activeGroups)
    {
        _playing = playing;
        PlayButton.Disabled = playing;
        StopButton.Disabled = !playing;
        FileButton.Disabled = playing;
        InstrumentSelect.Disabled = playing;

        if (playing && activeGroups != null)
        {
            StatusLabel.Text = $"Broadcasting to {activeGroups.Count} group(s)";
        }
        else
        {
            StatusLabel.Text = "Idle";
        }
    }
}
