using System.Collections.Generic;
using Content.Shared.Loudspeaker;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using static Robust.Client.UserInterface.Controls.BaseButton;
using FancyWindow = Content.Client.UserInterface.Controls.FancyWindow;

namespace Content.Client.Loudspeaker.UI;

[GenerateTypedNameReferences]
public sealed partial class LoudspeakerMenu : FancyWindow
{
    public event Action? OnFilePressed;
    public event Action? OnPlayPressed;
    public event Action? OnStopPressed;
    public event Action<bool>? OnLoopToggled;

    private readonly Dictionary<string, CheckBox> _groupCheckBoxes = new();

    public LoudspeakerMenu()
    {
        RobustXamlLoader.Load(this);

        FileButton.OnPressed += _ => OnFilePressed?.Invoke();
        PlayButton.OnPressed += _ => OnPlayPressed?.Invoke();
        StopButton.OnPressed += _ => OnStopPressed?.Invoke();
        LoopButton.OnToggled += args => OnLoopToggled?.Invoke(args.Pressed);

        StopButton.Disabled = true;
    }

    public void PopulateGroups(List<LoudspeakerGroupInfo> groups)
    {
        GroupContainer.RemoveAllChildren();
        _groupCheckBoxes.Clear();

        foreach (var group in groups)
        {
            var checkBox = new CheckBox
            {
                Text = $"{group.Name} ({group.SpeakerCount})",
            };
            _groupCheckBoxes[group.GroupId] = checkBox;
            GroupContainer.AddChild(checkBox);
        }
    }

    public List<ProtoId<LoudspeakerGroupPrototype>> GetSelectedGroups()
    {
        var selected = new List<ProtoId<LoudspeakerGroupPrototype>>();

        foreach (var (groupId, checkBox) in _groupCheckBoxes)
        {
            if (checkBox.Pressed)
                selected.Add(groupId);
        }

        return selected;
    }

    public void SetPlaying(bool playing, List<ProtoId<LoudspeakerGroupPrototype>>? activeGroups)
    {
        PlayButton.Disabled = playing;
        StopButton.Disabled = !playing;
        FileButton.Disabled = playing;

        if (playing && activeGroups != null)
        {
            StatusLabel.Text = $"Broadcasting to {activeGroups.Count} group(s)";
        }
        else
        {
            StatusLabel.Text = "Idle";
        }
    }
}
